[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[dev]
  command = "cd frontend && npm start"
  publish = "frontend/public"
  port = 3000
  targetPort = 3000
  autoLaunch = true
  framework = "#custom"

# Redirect API calls to functions (PROCESS THIS FIRST)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 

# Redirects for React Router (Catch-all for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 